# Main bg/fg
theme[main_bg]="{{colors.background.default.hex}}"
theme[main_fg]="{{colors.on_background.default.hex}}"

theme[title]="{{colors.primary.default.hex}}"
theme[hi_fg]="{{colors.primary.default.hex}}"

theme[selected_bg]="{{colors.primary_container.default.hex}}"
theme[selected_fg]="{{colors.on_primary_container.default.hex}}"

theme[inactive_fg]="{{colors.outline.default.hex}}"
theme[proc_misc]="{{colors.tertiary.default.hex}}"

theme[cpu_box]="{{colors.outline.default.hex}}"
theme[mem_box]="{{colors.outline.default.hex}}"
theme[net_box]="{{colors.outline.default.hex}}"
theme[proc_box]="{{colors.outline.default.hex}}"
theme[div_line]="{{colors.outline_variant.default.hex}}"

theme[temp_start]="{{colors.primary.default.hex}}"
theme[temp_mid]="{{colors.tertiary.default.hex}}"
theme[temp_end]="{{colors.error.default.hex}}"

theme[cpu_start]="{{colors.primary.default.hex}}"
theme[cpu_mid]="{{colors.secondary.default.hex}}"
theme[cpu_end]="{{colors.tertiary.default.hex}}"

theme[free_start]="{{colors.tertiary.default.hex}}"
theme[free_mid]=""
theme[free_end]="{{colors.primary.default.hex}}"

theme[cached_start]="{{colors.secondary.default.hex}}"
theme[cached_mid]=""
theme[cached_end]="{{colors.primary.default.hex}}"

theme[available_start]="{{colors.tertiary.default.hex}}"
theme[available_mid]=""
theme[available_end]="{{colors.error.default.hex}}"

theme[used_start]="{{colors.primary.default.hex}}"
theme[used_mid]=""
theme[used_end]="{{colors.tertiary.default.hex}}"

theme[download_start]="{{colors.primary.default.hex}}"
theme[download_mid]=""
theme[download_end]="{{colors.tertiary.default.hex}}"

theme[upload_start]="{{colors.secondary.default.hex}}"
theme[upload_mid]=""
theme[upload_end]="{{colors.primary.default.hex}}"

theme[process_start]="{{colors.primary.default.hex}}"
theme[process_mid]="{{colors.secondary.default.hex}}"
theme[process_end]="{{colors.tertiary.default.hex}}"
